"""
GraphQL methods to CRUD study in Dewrangle
"""

import os
import logging
from pprint import pformat

import gql

from d3b_api_client_cli.dewrangle.graphql.common import (
    exec_query,
)
from d3b_api_client_cli.dewrangle.graphql.study import (
    queries,
    mutations,
)
from d3b_api_client_cli.dewrangle.graphql.organization import (
    paginate_organizations,
)
from d3b_api_client_cli.config import (
    DEWRANGLE_DIR,
    IdTypes,
    DEWRANGLE_MAX_PAGE_SIZE,
)
from d3b_api_client_cli.utils import (
    write_json,
    kf_id_to_global_id,
    global_id_to_kf_id,
)
from d3b_api_client_cli.dewrangle.poll_job import (
    poll_descriptor_upsert_job,
)

logger = logging.getLogger(__name__)


def upsert_global_descriptors(
    dewrangle_study_id, study_file_id, skip_unavailable_descriptors=True
):
    """
    Trigger the operation to upsert global descriptors in Dewrangle

    :param study_file_id: The Dewrangle ID returned from uploading a study
    file to Dewrangle
    :type study_file_id: str
    :param skip_unavailable_descriptors: If true any errors due to a descriptor
    already having a global ID assigned will be ignored
    :type skip_unavailable_descriptors: boolean
    """
    logger.info(f"🛸 Upsert global descriptors for study file: {study_file_id}")
    variables = {
        "input": {
            "studyId": dewrangle_study_id,
            "studyFileIds": [{"id": study_file_id}],
            "skipUnavailableDescriptors": skip_unavailable_descriptors,
        }
    }
    initial_resp = exec_query(
        mutations.upsert_global_descriptors, variables=variables
    )
    job_id = initial_resp["globalDescriptorUpsert"]["job"]["id"]

    timeout_seconds = 60

    poll_result = poll_descriptor_upsert_job(
        job_id,
        timeout_seconds=timeout_seconds,
    )

    is_complete_within_timeout = poll_result["status"]
    final_job_state = poll_result["job"]

    if not is_complete_within_timeout:
        raise TimeoutError(
            f"Job {job_id} did not complete within {timeout_seconds} seconds."
        )

    if final_job_state.get("errors", {}).get("totalCount", 0) > 0:
        error_message = f"--- ❌ Job {job_id} failed on the server. ---"
        raise RuntimeError(error_message)

    return initial_resp


def upsert_study(variables, organization_id, kf_study_id=None):
    """
    Upsert study in Dewrangle

    :param variables: Study attributes (see Dewrangle graphql schema)
    :type variables: dict
    :param organization_id: Dewrangle ID of organization
    :type organization_id: str
    :param kf_study_id: Kids First study ID
    :type kf_study_id: str

    :rtype: dict
    :returns: the study
    """
    update = False
    if not kf_study_id:
        global_id = variables.get("globalId", "")
        kf_study_id = global_id_to_kf_id(global_id)

    study = get_study_by_kf_id(kf_study_id)
    if study:
        update = True
        if study["organization_id"] != organization_id:
            raise Exception(
                "❌ This study is already part of another organization:"
                f" {study['organization_id']}. You cannot change its"
                " organization"
            )

    params = {"input": variables}

    if update:
        key = "Update"
        params.update({"id": study["id"]})
        dwid = study["id"]
        resp = exec_query(mutations.update_study, variables=params)
    else:
        key = "Create"
        params["input"].update({"organizationId": organization_id})
        params.pop("id", None)
        resp = exec_query(mutations.create_study, variables=params)
        dwid = resp["studyCreate"]["study"]["id"]

    errors = resp.get(f"study{key}", {}).get("errors")
    if errors:
        logger.warning(f"‼️  {key} study failed:\n{pformat(resp)}")
    else:
        logger.info(f"✅ {key} study succeeded:\n{pformat(resp)}")

    result = resp[f"study{key}"]["study"]
    result["id"] = dwid
    result["organization_id"] = organization_id

    return result


def delete_study(_id, id_type=IdTypes.DEWRANGLE.value):
    """
    Delete study in Dewrangle

    :param node_id: Dewrangle node ID of the study
    :type node_id: str
    :param id_type: The system/service this ID was generated by. One of
    IdTypes
    :type id_type: str
    :rtype: dict
    :returns: the response
    """
    node_id = _id
    if id_type == IdTypes.KIDS_FIRST.value:
        study = get_study_by_kf_id(_id)
        node_id = study.get("id")
        if not node_id:
            logger.warning(
                "⚠️  Could not find associated dewrangle ID."
                f" Delete study {_id} ABORTED"
            )
            return

    resp = exec_query(mutations.delete_study, variables={"id": node_id})

    errors = resp.get("studyDelete", {}).get("errors")
    if errors:
        result = errors
        logger.warning(f"🚮 ‼️  Delete study failed:\n{pformat(resp)}")
    else:
        logger.info(f"🚮 Deleted study:\n{pformat(resp)}")

        result = resp["studyDelete"]["study"]
        result["id"] = node_id

    return result


def read_studies(output_dir=DEWRANGLE_DIR, log_output=True):
    """
    Fetch studies that the client has access to

    :rtype: dict
    :returns: the studies
    """
    data = paginate_studies()

    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, "Study.json")
        write_json(data, filepath)
        logger.info(f"✏️  Wrote {len(data)} study to {filepath}")

    if log_output:
        logger.info(f"🔬 Studies:\n{pformat(data)}")

    return data


def read_study(node_id):
    """
    Fetch study by node id

    :rtype: dict
    :returns: the study
    """
    variables = {"id": node_id}
    resp = exec_query(queries.study, variables=variables)
    study = resp.get("node", {})

    if study:
        logger.info(
            f"🔎  Found Dewrangle study {study['globalId']}:\n{pformat(study)}"
        )
    else:
        logger.warning(f"❌ Not Found: dewrangle study {node_id}")

    return study


def paginate_studies(
    organizations=None, study_page_size=DEWRANGLE_MAX_PAGE_SIZE
):
    """
    Fetch all studies in all organizations that the viewer has access to

    Use Relay graphql pagination
    """
    if not organizations:
        organizations = paginate_organizations()

    logger.info("📄 Paginating Dewrangle studies ...")

    studies = {}
    for org in organizations:
        variables = {"first": study_page_size, "id": org["id"]}
        resp = exec_query(queries.org_studies, variables=variables)

        count = 0
        has_next_page = True
        while has_next_page:
            org_studies = resp["node"]["studies"]["edges"]
            page_info = resp["node"]["studies"]["pageInfo"]

            count += len(org_studies)
            total = resp["node"]["studies"]["totalCount"]

            if not total:
                has_next_page = False
                continue

            logger.info(
                f"Collecting {count}/{total} studies for org {org['name']}"
            )
            # Add studies to ouput
            for s in org_studies:
                study = s["node"]
                study["organization_id"] = org["id"]
                kf_id = global_id_to_kf_id(study["globalId"])
                study["kf_id"] = kf_id
                studies[kf_id] = study

            # Fetch next page if there is one
            has_next_page = page_info["hasNextPage"]
            end_cursor = page_info["endCursor"]
            if has_next_page and end_cursor:
                variables.update({"after": end_cursor})
                resp = exec_query(queries.org_studies, variables=variables)

    return studies


def get_study_by_kf_id(kf_study_id):
    """
    Fetch study from Dewrangle
    """
    studies = paginate_studies()

    return studies.get(kf_study_id, {})
